# Generated by Django 3.0.6 on 2020-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FilePathField(blank=True, path='static/images'),
        ),
    ]
