# Generated by Django 3.0.6 on 2020-06-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0002_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
