# Generated by Django 3.0.7 on 2020-06-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0003_remove_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('emailid', models.EmailField(max_length=254)),
                ('mobileno', models.IntegerField(blank=True)),
                ('blog_category', models.IntegerField()),
                ('blog_title', models.TextField()),
                ('blog_detail', models.TextField()),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField()),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
