# Generated by Django 3.0.7 on 2020-06-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0004_blogrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
