# Generated by Django 3.0.7 on 2020-06-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0007_auto_20200619_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
