# Generated by Django 3.0.7 on 2020-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0008_auto_20200619_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='blog',
            name='Author',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
