# Generated by Django 3.0.7 on 2020-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0009_auto_20200619_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Author',
            field=models.TextField(default='Admin'),
        ),
    ]
