# Generated by Django 3.0.7 on 2020-06-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0011_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='my_blogs/static/blogimages/'),
        ),
    ]
