# Generated by Django 3.0.7 on 2020-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0012_auto_20200619_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrequest',
            name='mobileno',
            field=models.IntegerField(null=True),
        ),
    ]
