# Generated by Django 3.0.7 on 2020-06-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0013_auto_20200620_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrequest',
            name='mobileno',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
