# Generated by Django 3.0.7 on 2020-06-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0014_auto_20200620_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrequest',
            name='blog_category',
            field=models.TextField(),
        ),
    ]
