# Generated by Django 3.0.7 on 2020-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0015_auto_20200620_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
