# Generated by Django 3.0.7 on 2020-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0016_blogrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrequest',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
