# Generated by Django 3.0.7 on 2020-07-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0022_auto_20200702_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_video',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
