# Generated by Django 3.0.7 on 2020-07-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0024_auto_20200703_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrequest',
            name='edit_status',
            field=models.BooleanField(default=True),
        ),
    ]
