# Generated by Django 3.0.7 on 2020-07-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0025_blogrequest_edit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogrequest_id',
            field=models.IntegerField(default=0),
        ),
    ]
